name: Black Code Format

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**.py'

permissions:
  contents: read
  pull-requests: write

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Black Code Format
        uses: antoniogonzalezsuarez/black-action@v0.1.0-rc2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
            