name: Black Code Format

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**.py'

permissions:
  contents: read
  pull-requests: write

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install Black
        run: pip install black

      - name: Run Black Check
        id: black-check
        continue-on-error: true
        run: |
          black --check --verbose . > black_output.txt 2>&1 || true
          echo "BLACK_EXIT_CODE=$?" >> $GITHUB_ENV

      - name: Find existing comment
        uses: peter-evans/find-comment@v3
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '## Black Formatting Report'

      - name: Prepare comment body
        run: |
          echo "## Black Formatting Report" > comment.md
          echo "\`\`\`" >> comment.md
          cat black_output.txt >> comment.md
          echo "\`\`\`" >> comment.md
          if [ "$BLACK_EXIT_CODE" != "0" ]; then
            echo -e "\n⚠️ Some files need formatting. Please run black locally to fix the formatting." >> comment.md
          else
            echo -e "\n✅ All files are properly formatted!" >> comment.md
          fi

      - name: Update or create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-file: comment.md
          edit-mode: replace
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Exit with Black's status
        if: env.BLACK_EXIT_CODE != '0'
        run: exit 1 