name: wemake-python-styleguide

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**.py'

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install wemake-python-styleguide
        run: pip install wemake-python-styleguide

      - name: Run wemake-python-styleguide
        uses: wemake-services/wemake-python-styleguide@master
        with:
          reporter: 'github-pr-check'
          path: '.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 